package com.example.jetweather

val weatherCode = mapOf(
    -1 to "Trace Rain",
    0 to "Clear",
    1 to "Sunny",
    2 to "Partly Cloudy",
    3 to "Partly Cloudy",
    4 to "Not used",
    5 to "Mist",
    6 to "Fog",
    7 to "Cloudy",
    8 to "Overcast",
    9 to "Light Rain Showers",
    10 to "Light Rain Showers",
    11 to "Drizzle",
    12 to "Light Rain",
    13 to "Heavy Rain Shower",
    14 to "Heavy Rain Shower",
    15 to "Heavy Rain Shower",
    16 to "Sleet Shower",
    17 to "Sleet Shower",
    18 to "Sleet",
    19 to "Hail Shower",
    20 to "Hail Shower",
    21 to "Hail",
    22 to "Light Snow Shower",
    23 to "Light Snow Shower",
    24 to "Light Snow",
    25 to "Heavy Snow Shower",
    26 to "Heavy Snow Shower",
    27 to "Heavy Snow",
    28 to "Thunder Shower",
    29 to "Thunder Shower",
    30 to "Thunder",
)
