package com.example.jetweather.helper

val weatherCode = mapOf(
    0 to "Clear Sky",
    1 to "Clear",
    2 to "Partly Cloudy",
    3 to "Overcast",
    45 to "Fog",
    48 to "Fog",
    51 to "Light Drizzle",
    53 to "Drizzle",
    55 to "Heavy Drizzle",
    56 to "Light Freezing Drizzle",
    57 to "Dense Freezing Drizzle",
    61 to "Slight Rain",
    63 to "Rain",
    65 to "Heavy Rain",
    66 to "Light Freezing Rain",
    67 to "Dense Freezing Rain",
    71 to "Light Snowfall",
    73 to "Snowfall",
    75 to "Heavy Snowfall",
    77 to "Snow Grains",
    80 to "Light Rain Showers",
    81 to "Rain Showers",
    82 to "Heavy Rain Showers",
    85 to "Light Snow Showers",
    86 to "Heavy Snow Showers",
    95 to "Thunderstorm",
    96 to "Thunderstorm with Slight Hail",
    99 to "Thunderstorm with Heavy Hail"
)
